<?php
return [
    'Sgsp_Pay_Check_Res' => [
        'Sgsp_Api' => 'PayCheck',
        'MachineNo' => 1,
        'CallNo' => 2,
        'ListDetail' => [
          0 => [
            'TrkNo' => 1,
            'TrkName' => '徳川　家康',
            'TrkKana' => 'トクガワ　イエヤス',
            'Kingaku' => 1000,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          1 => [
            'TrkNo' => 2,
            'TrkName' => '宮本　武蔵',
            'TrkKana' => 'ミヤモト　ムサシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          2 => [
            'TrkNo' => 3,
            'TrkName' => '聖徳　太子',
            'TrkKana' => 'ショウトク　タイシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          3 => [
            'TrkNo' => 4,
            'TrkName' => '田中　太郎',
            'TrkKana' => 'タナカ　タロウ',
            'Kingaku' => 51400,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Check_Detail_Res' => [
        'Sgsp_Api' => 'PayCheckDetail',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Detail' => [
          0 => [
            'DispSortNo' => 0,
            'TrkNo' => 1,
            'ShohinName' => 'キャディー',
            'ZeiKbn' => 0,
            'Tanka' => 1000,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Status' => 0,
          ],
          1 => [
            'DispSortNo' => 0,
            'TrkNo' => 2,
            'ShohinName' => '*お土産A',
            'ZeiKbn' => 0,
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Status' => 0,
          ],
          2 => [
            'DispSortNo' => 0,
            'TrkNo' => 3,
            'ShohinName' => 'ゴルフボール',
            'ZeiKbn' => 0,
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Status' => 0,
          ],
          3 => [
            'DispSortNo' => 0,
            'TrkNo' => 4,
            'ShohinName' => 'クラブレンタル',
            'ZeiKbn' => 0,
            'Tanka' => 51400,
            'Suryo' => '+001.00',
            'Kingaku' => 51400,
            'Status' => 0,
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Res' => [
        'Sgsp_Api' => 'Pay',
        'MachineNo' => 1,
        'CallNo' => 2,
        'HostBillNo' => 6628,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Reset_Res' => [
        'Sgsp_Api' => 'PayReset',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Receipt_Res' => [
        'Sgsp_Api' => 'PayReceipt',
        'MachineNo' => 1,
        'CallNo' => 2,
        /*'ReceiptKbn' => 0,*/   
        'ListTax' => [
          0 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'T',
            'ShohinName' => '明細合計金額',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 14334,
            'Comment1' => 'DetailKbn= T Comment1 of TrkNo= 0',
            'Comment2' => 'DetailKbn= T Comment2 of TrkNo= 0',
            'Comment3' => 'DetailKbn= T Comment3 of TrkNo= 0',
            'Comment4' => 'DetailKbn= T Comment4 of TrkNo= 0',
            'Comment5' => 'DetailKbn= T Comment5 of TrkNo= 0',
            'Comment6' => 'DetailKbn= T Comment6 of TrkNo= 0',
            'Comment7' => 'DetailKbn= T Comment7 of TrkNo= 0',
            'Comment8' => 'DetailKbn= T Comment8 of TrkNo= 0',
          ],
          1 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'R',
            'ShohinName' => '領収金額',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 14334,
            'Comment1' => 'DetailKbn= R Comment1 of TrkNo= 0',
            'Comment2' => 'DetailKbn= R Comment2 of TrkNo= 0',
            'Comment3' => 'DetailKbn= R Comment3 of TrkNo= 0',
            'Comment4' => 'DetailKbn= R Comment4 of TrkNo= 0',
            'Comment5' => 'DetailKbn= R Comment5 of TrkNo= 0',
            'Comment6' => 'DetailKbn= R Comment6 of TrkNo= 0',
            'Comment7' => 'DetailKbn= R Comment7 of TrkNo= 0',
            'Comment8' => 'DetailKbn= R Comment8 of TrkNo= 0',
          ],
          2 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'U',
            'ShohinName' => '静岡県ゴルフ振興基金',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= U Comment1 of TrkNo= 0',
            'Comment2' => 'DetailKbn= U Comment2 of TrkNo= 0',
            'Comment3' => 'DetailKbn= U Comment3 of TrkNo= 0',
            'Comment4' => 'DetailKbn= U Comment4 of TrkNo= 0',
            'Comment5' => 'DetailKbn= U Comment5 of TrkNo= 0',
            'Comment6' => 'DetailKbn= U Comment6 of TrkNo= 0',
            'Comment7' => 'DetailKbn= U Comment7 of TrkNo= 0',
            'Comment8' => 'DetailKbn= U Comment8 of TrkNo= 0',
          ],
          3 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'C',
            'ShohinName' => '内消費税',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= C Comment1 of TrkNo= 0',
            'Comment2' => 'DetailKbn= C Comment2 of TrkNo= 0',
            'Comment3' => 'DetailKbn= C Comment3 of TrkNo= 0',
            'Comment4' => 'DetailKbn= C Comment4 of TrkNo= 0',
            'Comment5' => 'DetailKbn= C Comment5 of TrkNo= 0',
            'Comment6' => 'DetailKbn= C Comment6 of TrkNo= 0',
            'Comment7' => 'DetailKbn= C Comment7 of TrkNo= 0',
            'Comment8' => 'DetailKbn= C Comment8 of TrkNo= 0',
          ],
          4 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 1,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => 'キャディー',
            'Tanka' => 1000,
            'Suryo' => '+003.00',
            'Kingaku' => 3000,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 0, RowNo = 1',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 0, RowNo = 1',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 0, RowNo = 1',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 0, RowNo = 1',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 0, RowNo = 1',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 0, RowNo = 1',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 0, RowNo = 1',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 0, RowNo = 1',
          ],
          5 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 2,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => 'ＳＰセット料金Ｇ',
            'Tanka' => 11334,
            'Suryo' => '+001.00',
            'Kingaku' => 11334,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 0, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 0, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 0, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 0, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 0, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 0, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 0, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 0, RowNo = 2',
          ],          
          6 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 3,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 0, RowNo = 3',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 0, RowNo = 3',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 0, RowNo = 3',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 0, RowNo = 3',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 0, RowNo = 3',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 0, RowNo = 3',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 0, RowNo = 3',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 0, RowNo = 3',
          ],
		  7 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026945,
            'RowNo' => 0,
            'TrkNo' => 1,
            'DetailKbn' => 'T',
            'ShohinName' => '合計TrkNo1',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 11334,
            'Comment1' => 'DetailKbn= T Comment1 of TrkNo= 1',
            'Comment2' => 'DetailKbn= T Comment2 of TrkNo= 1',
            'Comment3' => 'DetailKbn= T Comment3 of TrkNo= 1',
            'Comment4' => 'DetailKbn= T Comment4 of TrkNo= 1',
            'Comment5' => 'DetailKbn= T Comment5 of TrkNo= 1',
            'Comment6' => 'DetailKbn= T Comment6 of TrkNo= 1',
            'Comment7' => 'DetailKbn= T Comment7 of TrkNo= 1',
            'Comment8' => 'DetailKbn= T Comment8 of TrkNo= 1',
          ],
		  8 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026945,
            'RowNo' => 1,
            'TrkNo' => 1,
            'DetailKbn' => 'N',
            'ShohinName' => 'ＳＰセット料金Ｇ',
            'Tanka' => 11334	,
            'Suryo' => '+001.00',
            'Kingaku' => 11334,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 1, RowNo = 1',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 1, RowNo = 1',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 1, RowNo = 1',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 1, RowNo = 1',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 1, RowNo = 1',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 1, RowNo = 1',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 1, RowNo = 1',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 1, RowNo = 1',
          ],
          9 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026945,
            'RowNo' => 2,
            'TrkNo' => 1,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 1, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 1, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 1, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 1, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 1, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 1, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 1, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 1, RowNo = 2',
          ],
		  10 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026946,
            'RowNo' => 0,
            'TrkNo' => 2,
            'DetailKbn' => 'T',
            'ShohinName' => '合計TrkNo2',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= T Comment1 of TrkNo= 2',
            'Comment2' => 'DetailKbn= T Comment2 of TrkNo= 2',
            'Comment3' => 'DetailKbn= T Comment3 of TrkNo= 2',
            'Comment4' => 'DetailKbn= T Comment4 of TrkNo= 2',
            'Comment5' => 'DetailKbn= T Comment5 of TrkNo= 2',
            'Comment6' => 'DetailKbn= T Comment6 of TrkNo= 2',
            'Comment7' => 'DetailKbn= T Comment7 of TrkNo= 2',
            'Comment8' => 'DetailKbn= T Comment8 of TrkNo= 2',
          ],
		  11 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026946,
            'RowNo' => 1,
            'TrkNo' => 2,
            'DetailKbn' => 'N',
            'ShohinName' => 'キャディー2',
            'Tanka' => 1000	,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 2, RowNo = 1',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 2, RowNo = 1',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 2, RowNo = 1',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 2, RowNo = 1',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 2, RowNo = 1',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 2, RowNo = 1',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 2, RowNo = 1',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 2, RowNo = 1',
          ],
          12 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026946,
            'RowNo' => 2,
            'TrkNo' => 2,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税2',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 2, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 2, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 2, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 2, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 2, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 2, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 2, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 2, RowNo = 2',
          ],
		  13 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026947,
            'RowNo' => 0,
            'TrkNo' => 3,
            'DetailKbn' => 'T',
            'ShohinName' => '合計TrkNo3',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= T Comment1 of TrkNo= 3',
            'Comment2' => 'DetailKbn= T Comment2 of TrkNo= 3',
            'Comment3' => 'DetailKbn= T Comment3 of TrkNo= 3',
            'Comment4' => 'DetailKbn= T Comment4 of TrkNo= 3',
            'Comment5' => 'DetailKbn= T Comment5 of TrkNo= 3',
            'Comment6' => 'DetailKbn= T Comment6 of TrkNo= 3',
            'Comment7' => 'DetailKbn= T Comment7 of TrkNo= 3',
            'Comment8' => 'DetailKbn= T Comment8 of TrkNo= 3',
          ],
		  14 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026947,
            'RowNo' => 1,
            'TrkNo' => 3,
            'DetailKbn' => 'N',
            'ShohinName' => 'キャディー3',
            'Tanka' => 1000	,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 3, RowNo = 1',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 3, RowNo = 1',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 3, RowNo = 1',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 3, RowNo = 1',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 3, RowNo = 1',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 3, RowNo = 1',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 3, RowNo = 1',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 3, RowNo = 1',
          ],
          15 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026947,
            'RowNo' => 2,
            'TrkNo' => 3,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税3',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 3, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 3, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 3, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 3, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 3, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 3, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 3, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 3, RowNo = 2',
          ],
		  16 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026948,
            'RowNo' => 0,
            'TrkNo' => 4,
            'DetailKbn' => 'T',
            'ShohinName' => '合計TrkNo4',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= T Comment1 of TrkNo= 4',
            'Comment2' => 'DetailKbn= T Comment2 of TrkNo= 4',
            'Comment3' => 'DetailKbn= T Comment3 of TrkNo= 4',
            'Comment4' => 'DetailKbn= T Comment4 of TrkNo= 4',
            'Comment5' => 'DetailKbn= T Comment5 of TrkNo= 4',
            'Comment6' => 'DetailKbn= T Comment6 of TrkNo= 4',
            'Comment7' => 'DetailKbn= T Comment7 of TrkNo= 4',
            'Comment8' => 'DetailKbn= T Comment8 of TrkNo= 4',
          ],
		  17 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026948,
            'RowNo' => 1,
            'TrkNo' => 4,
            'DetailKbn' => 'N',
            'ShohinName' => 'キャディー4',
            'Tanka' => 1000	,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 4, RowNo = 1',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 4, RowNo = 1',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 4, RowNo = 1',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 4, RowNo = 1',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 4, RowNo = 1',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 4, RowNo = 1',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 4, RowNo = 1',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 4, RowNo = 1',
          ],
          18 => [
            'ReceiptKbn' => 1,
            'ReceiptNo' => 10026948,
            'RowNo' => 2,
            'TrkNo' => 4,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税4',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 4, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 4, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 4, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 4, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 4, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 4, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 4, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 4, RowNo = 2',
          ],
          19 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 2,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*vuong1',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 4, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 4, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 4, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 4, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 4, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 4, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 4, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 4, RowNo = 2',
          ],
          20 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 2,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*vuong2',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 4, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 4, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 4, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 4, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 4, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 4, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 4, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 4, RowNo = 2',
          ],
          21 => [
            'ReceiptKbn' => 0,
            'ReceiptNo' => 10026944,
            'RowNo' => 2,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*vuong3',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'DetailKbn= N Comment1 of TrkNo= 4, RowNo = 2',
            'Comment2' => 'DetailKbn= N Comment2 of TrkNo= 4, RowNo = 2',
            'Comment3' => 'DetailKbn= N Comment3 of TrkNo= 4, RowNo = 2',
            'Comment4' => 'DetailKbn= N Comment4 of TrkNo= 4, RowNo = 2',
            'Comment5' => 'DetailKbn= N Comment5 of TrkNo= 4, RowNo = 2',
            'Comment6' => 'DetailKbn= N Comment6 of TrkNo= 4, RowNo = 2',
            'Comment7' => 'DetailKbn= N Comment7 of TrkNo= 4, RowNo = 2',
            'Comment8' => 'DetailKbn= N Comment8 of TrkNo= 4, RowNo = 2',
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Purchase_Res' => [
        'Sgsp_Api' => 'PayPurchase',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Purchase_Decision_Res' => [
        'Sgsp_Api' => 'PayPurchaseDecision',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_PointPay_Check_Res' => [
        'Sgsp_Api' => 'PointPayCheck',
        'MachineNo' => 1,
        'CallNo' => 2,
        'ListDetail' => [
          0 => [
            'TrkNo' => 1,
            'TrkName' => '徳川　家康',
            'TrkKana' => 'トクガワ　イエヤス',
            'Kingaku' => 1000,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          1 => [
            'TrkNo' => 2,
            'TrkName' => '宮本　武蔵',
            'TrkKana' => 'ミヤモト　ムサシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          2 => [
            'TrkNo' => 3,
            'TrkName' => '聖徳　太子',
            'TrkKana' => 'ショウトク　タイシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          3 => [
            'TrkNo' => 4,
            'TrkName' => '田中　太郎',
            'TrkKana' => 'タナカ　タロウ',
            'Kingaku' => 51400,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
        ],
        'BillingAmount' => 52600,
        'UsePoints' => 0,
        'UsePointsKind' => 0,
        'PointBalance' => 100000,
        'UsePointsLimitUpper' => 20,
        'UsePointsLimitLower' => 10,
        'UsePointsUnit' => 10,
        'UsePointsMessage' => '1ポイントにつき1円の割引が可能です。',
        'Status' => 0,
        'Message' => '000000',
    ],
];
