<?php
return [
    'Sgsp_Pay_Check_Res' => [
        'Sgsp_Api' => 'PayCheck',
        'MachineNo' => 1,
        'CallNo' => 2,
        'ListDetail' => [
          0 => [
            'TrkNo' => 1,
            'TrkName' => '徳川　家康',
            'TrkKana' => 'トクガワ　イエヤス',
            'Kingaku' => 1000,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          1 => [
            'TrkNo' => 2,
            'TrkName' => '宮本　武蔵',
            'TrkKana' => 'ミヤモト　ムサシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          2 => [
            'TrkNo' => 3,
            'TrkName' => '聖徳　太子',
            'TrkKana' => 'ショウトク　タイシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          3 => [
            'TrkNo' => 4,
            'TrkName' => '田中　太郎',
            'TrkKana' => 'タナカ　タロウ',
            'Kingaku' => 51400,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Check_Detail_Res' => [
        'Sgsp_Api' => 'PayCheckDetail',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Detail' => [
          0 => [
            'DispSortNo' => 0,
            'TrkNo' => 1,
            'ShohinName' => 'キャディー',
            'ZeiKbn' => 0,
            'Tanka' => 1000,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Status' => 0,
          ],
          1 => [
            'DispSortNo' => 0,
            'TrkNo' => 2,
            'ShohinName' => '*お土産A',
            'ZeiKbn' => 0,
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Status' => 0,
          ],
          2 => [
            'DispSortNo' => 0,
            'TrkNo' => 3,
            'ShohinName' => 'ゴルフボール',
            'ZeiKbn' => 0,
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Status' => 0,
          ],
          3 => [
            'DispSortNo' => 0,
            'TrkNo' => 4,
            'ShohinName' => 'クラブレンタル',
            'ZeiKbn' => 0,
            'Tanka' => 51400,
            'Suryo' => '+001.00',
            'Kingaku' => 51400,
            'Status' => 0,
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Res' => [
        'Sgsp_Api' => 'Pay',
        'MachineNo' => 1,
        'CallNo' => 2,
        'HostBillNo' => 6628,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Reset_Res' => [
        'Sgsp_Api' => 'PayReset',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Receipt_Res' => [
        'Sgsp_Api' => 'PayReceipt',
        'MachineNo' => 1,
        'CallNo' => 2,
        'ReceiptKbn' => 0,
        'ReceiptNo' => 10026944,
        'ListTax' => [
          0 => [
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'T',
            'ShohinName' => '明細合計金額',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 52600,
            'Comment1' => 'a',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          1 => [
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'R',
            'ShohinName' => '領収金額',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 52600,
            'Comment1' => 'e',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          2 => [
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'U',
            'ShohinName' => '静岡県ゴルフ振興基金',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => 'f',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          3 => [
            'RowNo' => 0,
            'TrkNo' => 0,
            'DetailKbn' => 'C',
            'ShohinName' => '内消費税',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          4 => [
            'RowNo' => 1,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => 'キャディー',
            'Tanka' => 1000,
            'Suryo' => '+001.00',
            'Kingaku' => 1000,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          5 => [
            'RowNo' => 2,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*お土産A',
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          6 => [
            'RowNo' => 3,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => 'ゴルフボール',
            'Tanka' => 100,
            'Suryo' => '+001.00',
            'Kingaku' => 100,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          7 => [
            'RowNo' => 4,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => 'クラブレンタル',
            'Tanka' => 51400,
            'Suryo' => '+001.00',
            'Kingaku' => 51400,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
          8 => [
            'RowNo' => 5,
            'TrkNo' => 0,
            'DetailKbn' => 'N',
            'ShohinName' => '*消費税',
            'Tanka' => 0,
            'Suryo' => '+000.00',
            'Kingaku' => 0,
            'Comment1' => '',
            'Comment2' => '',
            'Comment3' => '',
            'Comment4' => '',
            'Comment5' => '',
            'Comment6' => '',
            'Comment7' => '',
            'Comment8' => '',
          ],
        ],
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Purchase_Res' => [
        'Sgsp_Api' => 'PayPurchase',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_Pay_Purchase_Decision_Res' => [
        'Sgsp_Api' => 'PayPurchaseDecision',
        'MachineNo' => 1,
        'CallNo' => 2,
        'Status' => 0,
        'Message' => '000000',
    ],
    'Sgsp_PointPay_Check_Res' => [
        'Sgsp_Api' => 'PointPayCheck',
        'MachineNo' => 1,
        'CallNo' => 2,
        'ListDetail' => [
          0 => [
            'TrkNo' => 1,
            'TrkName' => '徳川　家康',
            'TrkKana' => 'トクガワ　イエヤス',
            'Kingaku' => 1000,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          1 => [
            'TrkNo' => 2,
            'TrkName' => '宮本　武蔵',
            'TrkKana' => 'ミヤモト　ムサシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          2 => [
            'TrkNo' => 3,
            'TrkName' => '聖徳　太子',
            'TrkKana' => 'ショウトク　タイシ',
            'Kingaku' => 100,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
          3 => [
            'TrkNo' => 4,
            'TrkName' => '田中　太郎',
            'TrkKana' => 'タナカ　タロウ',
            'Kingaku' => 51400,
            'Status' => 0,
            'Message' => '',
            'PayDoneFlag' => 0,
          ],
        ],
        'BillingAmount' => 52600,
        'UsePoints' => 0,
        'UsePointsKind' => 0,
        'PointBalance' => 100000,
        'UsePointsLimitUpper' => 50000,
        'UsePointsLimitLower' => 10,
        'UsePointsUnit' => 10,
        'UsePointsMessage' => '1ポイントにつき1円の割引が可能です。',
        'Status' => 0,
        'Message' => '000000',
    ],
];
